---
title: "Problem set calculations"
author: "Filip Mellgren"
date: '2019-09-30'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
# Problem 1
q <- 107 # from solution
rev <- (226 - q)*q
cost <- (12)*q + 6000
Profit <- rev - cost
Profit

```

```{r}
# C
t <- 114
q <- (226 -t) / 2
Pi_M <- (226 - t)*(t/2 - 1) - 6000

Pi_A <- (226^2-t^2)/4 - t*(226-t)/2


# Last part
p <- 170
t = 114
q = 56


```

```{r}
# Problem 5 a
# Checking for optimal solution, assuming formulation is correct
p2 <- seq(0,1,0.0001)
pp2 <- (p2 + 1)/2
q2 <- pp2 - p2
qq2 <- 1 - pp2
  
Pi <- p2*q2 + pp2*qq2

as_tibble(p2, Pi) %>% ggplot(aes(x = p2, y = Pi)) + geom_point()
which.max(Pi)
p2 <- 1/3
```

```{r}
# 5c
library(tidyverse)
delta <- seq(0,1,0.01)
p1 <- (4 - delta^2) / (2*(4+delta))
v <- (2+delta)/(4+delta)
p2hat <- v
p2 <- v/2

Pi2 <- p2*(v-p2) + v*(1-v)
Pi1 <- p1*(1-v)
Profit_b <- Pi1 + delta * Pi2

Profit_c = 1/2*(1-1/2) + delta*1/2*(1-1/2)

as_tibble(cbind(delta, Profit_b, Profit_c)) %>% 
  gather(Profit_b, Profit_c, key = "BBPD", value = "Profit") %>%
  ggplot(aes(x = delta, y = Profit, color = BBPD)) + 
  geom_line() +
  labs(title = "Discriminating firms earn less than firms able to commit to prices",
       x = "Discounting factor delta", y = "Profit",
       subtitle = "The effect increases as consumers and firms value the future more") +
  theme_classic()
ggsave("Plot_part_c.png")

```

touch README.md
git init
git add README.md
git commit -m "first commit"
git remote add origin https://github.com/filipmellgren/IO_D.git
git clone origin master

```{r}
library(tidyverse)
# Problem 5d, parameters;
delta <- seq(0,1,0.001)

# Case C, the comparison has the following values:
profitsc <- (1+delta)/4
pc <- 1/2
CSc = (1+delta) * ((1-pc)^2)/2 
Wc <- profitsc + CSc

# Case A
p1 <- (1+delta)/(2+3*delta/2)
p2 = p1/2
phat2 = p1
CSa = (1-p1)^2/2 + delta * (((p1-p2)^2)/2 + ((1-p1)^2)/2)
profitsa = p1*(1-p1) + delta * (p2*(p1-p2) + phat2*(1-phat2))
Wa = profitsa + CSa

# Comparison Case A
Welfare_A <- Wa - Wc
CS_A <- CSa - CSc 

# Case B
p1b <- (4-delta^2)/(2*(4+delta))
v <- (2+delta)/(4+delta)
p2b <- v/2
profitsb <- p1b*(1-v) + delta*((v/2)^2 + v*(1-v))

CSb1 <- ((1-p1b)*(1-v))/2
CSb2 <- ((v-p2b)^2)/2 + ((1-v)^2)/2

Wb <- profitsb + CSb1 + delta*CSb2

# Comparison case B
Welfare_B <- Wb - Wc 
CS_B <- CSb1 + delta * CSb2 - CSc

# Plot
df <- cbind(delta, Welfare_A, CS_A, Welfare_B, CS_B) %>% as_tibble() %>% 
  gather(key = "Comparison", value = "Welfare", Welfare_A, CS_A, Welfare_B, CS_B) 

df %>% 
  ggplot(aes(x = delta, y = Welfare, color = Comparison)) + geom_line() +
  theme_minimal() +
  labs(title = "Effects of enacting BBPD",
       subtitle = "Lines show welfare with BBPD compared to welfare without BBPD",
       y = "Net welfare effect")
ggsave("BBPD_effect.png")
```


```{r}
d <- seq(0,1,0.001)
p1 <- (4 -d^2)/(2*(d^2-d+4))
v <- p1/(1-d/2)
```